### ISSUE TITLE
Request to change the name

### ISSUE THREAD

**Issue by kevinhermawan** [gregorym/ollamac-pro#1]
Hey there,

I hope you're doing well. I wanted to take a moment to thank you for your interest in my project and for creating your version of it. It's great to see the community engagement and the effort you've put into building upon the work that I started.

However, I've come to know that your forked version is being shared under the same name as my original project, Ollamac. While I understand that the project is licensed under the MIT License, which allows forking and commercial use, I would like to request that you change the name of your forked project to avoid confusion with the original Ollamac project.

It would be great if we could maintain different names for our projects, to avoid confusion among users and to ensure that each project is recognized for its distinctive contribution to the community. I believe this approach will be beneficial for both projects and the users who rely on them.

I'm committed to keeping the original Ollamac project free and open-source and welcome contributions from the community to further enhance its functionality and usability. If you have any questions or would like to discuss this further, please feel free to reach out to me.

Thank you for your understanding and cooperation.

Best regards,

Kevin Hermawan
Creator of [Ollamac](https://github.com/kevinhermawan/Ollamac).

**Comment by kingwpf** [comment]
This guy is a thief.

**Comment by unoflavora** [comment]
this guy @gregorym is a scam.

**Comment by pmarreck** [comment]
this is a perfect illustration of why you need to get your licensing right before nerd megadicks like @gregorym exercise their nihilism against you
