### ISSUE TITLE
Remote server on LAN doesn't work.

### ISSUE THREAD

**Issue by ZedOud** [gregorym/ollamac-pro#2]
After adding a remote server on a LAN, no connection is made, no feedback is given whether a connection is made, and the model list does not populate in the new chat interface.

**Comment by ZedOud** [comment]
I'll add that localhost does work.
![Screenshot 2024-04-23 at 4 22 24 PM](https://github.com/gregorym/ollamac-pro/assets/7321904/6a1eadb9-2bf1-4a54-8d83-5a2f40c370b1)

**Comment by gregorym** [comment]
@ZedOud Could you share the remote url privately with me by email? greg@ollamac.com

**Comment by gregorym** [comment]
This is "fixed" in the latest version. 
You won't be able to access the chat screen unless we're able to create a successful connection.
